mod block;
mod chain;
mod cross;
mod lines;

use std::iter;

use swash::zeno::{Placement, Vector};

use super::GlyphMetrics;

pub use chain::{Chain, ChainList};

mod base_id {
    pub const BOX_DRAWING: u16 = 1024;
    pub const BLOCK_ELEMENTS: u16 = BOX_DRAWING + 0xB3;
    pub const BLOCK_SEXTANTS: u16 = BLOCK_ELEMENTS + 0x6D;
    pub const BLOCK_OCTANTS: u16 = BLOCK_SEXTANTS + 0x3C;
}

type Image = (Vec<u8>, Placement);
type ImageCluster = Vec<Image>;
type Render = fn(&GlyphMetrics, Vector) -> ImageCluster;

pub struct GlyphDrawing {
    pub id: u16,
    pub key: char,
    pub render: Render,
}

impl GlyphDrawing {
    pub fn get(key: char) -> Option<Self> {
        let lookups = [
            Self::try_box_drawing_components,
            Self::try_block_elements,
            Self::try_block_sextants,
            Self::try_block_octants,
        ];

        lookups
            .into_iter()
            .zip(iter::repeat(key))
            .flat_map(|(lookup, key)| lookup(key))
            .next()
    }

    fn try_box_drawing_components(key: char) -> Option<Self> {
        let result: Option<(_, Render)> = match key {
            ..='\u{24FF}' => None,
            '\u{2500}' => Some((0x5F, lines::light_horizontal)),
            '\u{2501}' => Some((0x2F, lines::heavy_horizontal)),
            '\u{2502}' => Some((0x72, lines::light_vertical)),
            '\u{2503}' => Some((0x41, lines::heavy_vertical)),
            '\u{2504}' => Some((0x67, lines::light_triple_dash_horizontal)),
            '\u{2505}' => Some((0x36, lines::heavy_triple_dash_horizontal)),
            '\u{2506}' => Some((0x68, lines::light_triple_dash_vertical)),
            '\u{2507}' => Some((0x37, lines::heavy_triple_dash_vertical)),
            '\u{2508}' => Some((0x64, lines::light_quadruple_dash_horizontal)),
            '\u{2509}' => Some((0x33, lines::heavy_quadruple_dash_horizontal)),
            '\u{250A}' => Some((0x65, lines::light_quadruple_dash_vertical)),
            '\u{250B}' => Some((0x34, lines::heavy_quadruple_dash_vertical)),
            '\u{250C}' => Some((0x5D, lines::light_down_and_right)),
            '\u{250D}' => Some((0x20, lines::down_light_and_right_heavy)),
            '\u{250E}' => Some((0x14, lines::down_heavy_and_right_light)),
            '\u{250F}' => Some((0x2D, lines::heavy_down_and_right)),
            '\u{2510}' => Some((0x5C, lines::light_down_and_left)),
            '\u{2511}' => Some((0x1C, lines::down_light_and_left_heavy)),
            '\u{2512}' => Some((0x10, lines::down_heavy_and_left_light)),
            '\u{2513}' => Some((0x2C, lines::heavy_down_and_left)),
            '\u{2514}' => Some((0x6D, lines::light_up_and_right)),
            '\u{2515}' => Some((0x9C, lines::up_light_and_right_heavy)),
            '\u{2516}' => Some((0x90, lines::up_heavy_and_right_light)),
            '\u{2517}' => Some((0x3C, lines::heavy_up_and_right)),
            '\u{2518}' => Some((0x6C, lines::light_up_and_left)),
            '\u{2519}' => Some((0x98, lines::up_light_and_left_heavy)),
            '\u{251A}' => Some((0x8C, lines::up_heavy_and_left_light)),
            '\u{251B}' => Some((0x39, lines::heavy_up_and_left)),
            '\u{251C}' => Some((0x71, lines::light_vertical_and_right)),
            '\u{251D}' => Some((0xAE, lines::vertical_light_and_right_heavy)),
            '\u{251E}' => Some((0x8E, lines::up_heavy_and_right_down_light)),
            '\u{251F}' => Some((0x16, lines::down_heavy_and_right_up_light)),
            '\u{2520}' => Some((0xA8, lines::vertical_heavy_and_right_light)),
            '\u{2521}' => Some((0x22, lines::down_light_and_right_up_heavy)),
            '\u{2522}' => Some((0x9A, lines::up_light_and_right_down_heavy)),
            '\u{2523}' => Some((0x40, lines::heavy_vertical_and_right)),
            '\u{2524}' => Some((0x70, lines::light_vertical_and_left)),
            '\u{2525}' => Some((0xAC, lines::vertical_light_and_left_heavy)),
            '\u{2526}' => Some((0x8A, lines::up_heavy_and_left_down_light)),
            '\u{2527}' => Some((0x12, lines::down_heavy_and_left_up_light)),
            '\u{2528}' => Some((0xA6, lines::vertical_heavy_and_left_light)),
            '\u{2529}' => Some((0x1E, lines::down_light_and_left_up_heavy)),
            '\u{252A}' => Some((0x96, lines::up_light_and_left_down_heavy)),
            '\u{252B}' => Some((0x3F, lines::heavy_vertical_and_left)),
            '\u{252C}' => Some((0x5B, lines::light_down_and_horizontal)),
            '\u{252D}' => Some((0x44, lines::left_heavy_and_right_down_light)),
            '\u{252E}' => Some((0x75, lines::right_heavy_and_left_down_light)),
            '\u{252F}' => Some((0x1A, lines::down_light_and_horizontal_heavy)),
            '\u{2530}' => Some((0x0E, lines::down_heavy_and_horizontal_light)),
            '\u{2531}' => Some((0x7B, lines::right_light_and_left_down_heavy)),
            '\u{2532}' => Some((0x4A, lines::left_light_and_right_down_heavy)),
            '\u{2533}' => Some((0x2B, lines::heavy_down_and_horizontal)),
            '\u{2534}' => Some((0x6B, lines::light_up_and_horizontal)),
            '\u{2535}' => Some((0x46, lines::left_heavy_and_right_up_light)),
            '\u{2536}' => Some((0x77, lines::right_heavy_and_left_up_light)),
            '\u{2537}' => Some((0x94, lines::up_light_and_horizontal_heavy)),
            '\u{2538}' => Some((0x88, lines::up_heavy_and_horizontal_light)),
            '\u{2539}' => Some((0x7D, lines::right_light_and_left_up_heavy)),
            '\u{253A}' => Some((0x4C, lines::left_light_and_right_up_heavy)),
            '\u{253B}' => Some((0x38, lines::heavy_up_and_horizontal)),
            '\u{253C}' => Some((0x6F, lines::light_vertical_and_horizontal)),
            '\u{253D}' => Some((0x48, lines::left_heavy_and_right_vertical_light)),
            '\u{253E}' => Some((0x79, lines::right_heavy_and_left_vertical_light)),
            '\u{253F}' => Some((0xAA, lines::vertical_light_and_horizontal_heavy)),
            '\u{2540}' => Some((0x86, lines::up_heavy_and_down_horizontal_light)),
            '\u{2541}' => Some((0x18, lines::down_heavy_and_up_horizontal_light)),
            '\u{2542}' => Some((0xA4, lines::vertical_heavy_and_horizontal_light)),
            '\u{2543}' => Some((0x50, lines::left_up_heavy_and_right_down_light)),
            '\u{2544}' => Some((0x81, lines::right_up_heavy_and_left_down_light)),
            '\u{2545}' => Some((0x42, lines::left_down_heavy_and_right_up_light)),
            '\u{2546}' => Some((0x73, lines::right_down_heavy_and_left_up_light)),
            '\u{2547}' => Some((0x24, lines::down_light_and_up_horizontal_heavy)),
            '\u{2548}' => Some((0x92, lines::up_light_and_down_horizontal_heavy)),
            '\u{2549}' => Some((0x7F, lines::right_light_and_left_vertical_heavy)),
            '\u{254A}' => Some((0x4E, lines::left_light_and_right_vertical_heavy)),
            '\u{254B}' => Some((0x3E, lines::heavy_vertical_and_horizontal)),
            '\u{254C}' => Some((0x59, lines::light_double_dash_horizontal)),
            '\u{254D}' => Some((0x29, lines::heavy_double_dash_horizontal)),
            '\u{254E}' => Some((0x5A, lines::light_double_dash_vertical)),
            '\u{254F}' => Some((0x2A, lines::heavy_double_dash_vertical)),
            '\u{2550}' => Some((0x03, lines::double_horizontal)),
            '\u{2551}' => Some((0x0A, lines::double_vertical)),
            '\u{2552}' => Some((0x28, lines::down_single_and_right_double)),
            '\u{2553}' => Some((0x0D, lines::down_double_and_right_single)),
            '\u{2554}' => Some((0x02, lines::double_down_and_right)),
            '\u{2555}' => Some((0x27, lines::down_single_and_left_double)),
            '\u{2556}' => Some((0x0C, lines::down_double_and_left_single)),
            '\u{2557}' => Some((0x01, lines::double_down_and_left)),
            '\u{2558}' => Some((0xA0, lines::up_single_and_right_double)),
            '\u{2559}' => Some((0x85, lines::up_double_and_right_single)),
            '\u{255A}' => Some((0x06, lines::double_up_and_right)),
            '\u{255B}' => Some((0x9F, lines::up_single_and_left_double)),
            '\u{255C}' => Some((0x84, lines::up_double_and_left_single)),
            '\u{255D}' => Some((0x05, lines::double_up_and_left)),
            '\u{255E}' => Some((0xB2, lines::vertical_single_and_right_double)),
            '\u{255F}' => Some((0xA3, lines::vertical_double_and_right_single)),
            '\u{2560}' => Some((0x09, lines::double_vertical_and_right)),
            '\u{2561}' => Some((0xB1, lines::vertical_single_and_left_double)),
            '\u{2562}' => Some((0xA2, lines::vertical_double_and_left_single)),
            '\u{2563}' => Some((0x08, lines::double_vertical_and_left)),
            '\u{2564}' => Some((0x26, lines::down_single_and_horizontal_double)),
            '\u{2565}' => Some((0x0B, lines::down_double_and_horizontal_single)),
            '\u{2566}' => Some((0x00, lines::double_down_and_horizontal)),
            '\u{2567}' => Some((0x9E, lines::up_single_and_horizontal_double)),
            '\u{2568}' => Some((0x83, lines::up_double_and_horizontal_single)),
            '\u{2569}' => Some((0x04, lines::double_up_and_horizontal)),
            '\u{256A}' => Some((0xB0, lines::vertical_single_and_horizontal_double)),
            '\u{256B}' => Some((0xA1, lines::vertical_double_and_horizontal_single)),
            '\u{256C}' => Some((0x07, lines::double_vertical_and_horizontal)),
            '\u{256D}' => Some((0x53, lines::light_arc_down_and_right)),
            '\u{256E}' => Some((0x52, lines::light_arc_down_and_left)),
            '\u{256F}' => Some((0x54, lines::light_arc_up_and_left)),
            '\u{2570}' => Some((0x55, lines::light_arc_up_and_right)),
            '\u{2571}' => Some((0x58, cross::light_diagonal_upper_right_to_lower_left)),
            '\u{2572}' => Some((0x57, cross::light_diagonal_upper_left_to_lower_right)),
            '\u{2573}' => Some((0x56, cross::light_diagonal_cross)),
            '\u{2574}' => Some((0x63, lines::light_left)),
            '\u{2575}' => Some((0x6E, lines::light_up)),
            '\u{2576}' => Some((0x66, lines::light_right)),
            '\u{2577}' => Some((0x5E, lines::light_down)),
            '\u{2578}' => Some((0x32, lines::heavy_left)),
            '\u{2579}' => Some((0x3D, lines::heavy_up)),
            '\u{257A}' => Some((0x35, lines::heavy_right)),
            '\u{257B}' => Some((0x2E, lines::heavy_down)),
            '\u{257C}' => Some((0x61, lines::light_left_and_heavy_right)),
            '\u{257D}' => Some((0x69, lines::light_up_and_heavy_down)),
            '\u{257E}' => Some((0x30, lines::heavy_left_and_light_right)),
            '\u{257F}' => Some((0x3A, lines::heavy_up_and_light_down)),
            '\u{2580}'..='\u{D7FF}' | '\u{E000}'..='\u{1FBAE}' => None,
            '\u{1FBAF}' => Some((0x60, lines::light_horizontal_with_vertical_stroke)),
            '\u{1FBB0}'.. => None,
        };

        result.map(|(id_offset, render)| Self {
            id: base_id::BOX_DRAWING + id_offset,
            key,
            render,
        })
    }

    #[rustfmt::skip]
    fn try_block_elements(key: char) -> Option<Self> {
        let result: Option<(_, Render)> = match key {
            ..='\u{257F}' => None,
            '\u{2580}' => Some((0x55, block::upper_half_block)),
            '\u{2581}' => Some((0x2C, block::lower_one_eighth_block)),
            '\u{2582}' => Some((0x2D, block::lower_one_quarter_block)),
            '\u{2583}' => Some((0x30, block::lower_three_eighths_block)),
            '\u{2584}' => Some((0x23, block::lower_half_block)),
            '\u{2585}' => Some((0x22, block::lower_five_eighths_block)),
            '\u{2586}' => Some((0x31, block::lower_three_quarters_block)),
            '\u{2587}' => Some((0x2F, block::lower_seven_eighths_block)),
            '\u{2588}' => Some((0x02, block::full_block)),
            '\u{2589}' => Some((0x18, block::left_seven_eighths_block)),
            '\u{258A}' => Some((0x1A, block::left_three_quarters_block)),
            '\u{258B}' => Some((0x0F, block::left_five_eighths_block)),
            '\u{258C}' => Some((0x10, block::left_half_block)),
            '\u{258D}' => Some((0x19, block::left_three_eighths_block)),
            '\u{258E}' => Some((0x16, block::left_one_quarter_block)),
            '\u{258F}' => Some((0x15, block::left_one_eighth_block)),
            '\u{2590}' => Some((0x44, block::right_half_block)),
            '\u{2591}' => Some((0x1E, block::light_shade)),
            '\u{2592}' => Some((0x34, block::medium_shade)),
            '\u{2593}' => Some((0x01, block::dark_shade)),
            '\u{2594}' => Some((0x5F, block::upper_one_eighth_block)),
            '\u{2595}' => Some((0x48, block::right_one_eighth_block)),
            '\u{2596}' => Some((0x37, block::quadrant_lower_left)),
            '\u{2597}' => Some((0x38, block::quadrant_lower_right)),
            '\u{2598}' => Some((0x3D, block::quadrant_upper_left)),
            '\u{2599}' => Some((0x39, block::quadrant_upper_left_and_lower_left_and_lower_right)),
            '\u{259A}' => Some((0x3A, block::quadrant_upper_left_and_lower_right)),
            '\u{259B}' => Some((0x3B, block::quadrant_upper_left_and_upper_right_and_lower_left)),
            '\u{259C}' => Some((0x3C, block::quadrant_upper_left_and_upper_right_and_lower_right)),
            '\u{259D}' => Some((0x40, block::quadrant_upper_right)),
            '\u{259E}' => Some((0x3F, block::quadrant_upper_right_and_lower_left)),
            '\u{259F}' => Some((0x3E, block::quadrant_upper_right_and_lower_left_and_lower_right)),
            '\u{25A0}'..='\u{D7FF}' | '\u{E000}'..='\u{1CE8F}' => None,
            '\u{1CE90}' => Some((0x5A, block::upper_left_one_sixteenth_block)),
            '\u{1CE91}' => Some((0x50, block::upper_centre_left_one_sixteenth_block)),
            '\u{1CE92}' => Some((0x52, block::upper_centre_right_one_sixteenth_block)),
            '\u{1CE93}' => Some((0x61, block::upper_right_one_sixteenth_block)),
            '\u{1CE94}' => Some((0x5D, block::upper_middle_left_one_sixteenth_block)),
            '\u{1CE95}' => Some((0x5B, block::upper_middle_centre_left_one_sixteenth_block)),
            '\u{1CE96}' => Some((0x5C, block::upper_middle_centre_right_one_sixteenth_block)),
            '\u{1CE97}' => Some((0x5E, block::upper_middle_right_one_sixteenth_block)),
            '\u{1CE98}' => Some((0x2A, block::lower_middle_left_one_sixteenth_block)),
            '\u{1CE99}' => Some((0x28, block::lower_middle_centre_left_one_sixteenth_block)),
            '\u{1CE9A}' => Some((0x29, block::lower_middle_centre_right_one_sixteenth_block)),
            '\u{1CE9B}' => Some((0x2B, block::lower_middle_right_one_sixteenth_block)),
            '\u{1CE9C}' => Some((0x27, block::lower_left_one_sixteenth_block)),
            '\u{1CE9D}' => Some((0x1F, block::lower_centre_left_one_sixteenth_block)),
            '\u{1CE9E}' => Some((0x21, block::lower_centre_right_one_sixteenth_block)),
            '\u{1CE9F}' => Some((0x2E, block::lower_right_one_sixteenth_block)),
            '\u{1CEA0}' => Some((0x45, block::right_half_lower_one_quarter_block)),
            '\u{1CEA1}' => Some((0x4D, block::right_three_quarters_lower_one_quarter_block)),
            '\u{1CEA2}' => Some((0x1B, block::left_three_quarters_lower_one_quarter_block)),
            '\u{1CEA3}' => Some((0x12, block::left_half_lower_one_quarter_block)),
            '\u{1CEA4}' => Some((0x24, block::lower_half_left_one_quarter_block)),
            '\u{1CEA5}' => Some((0x32, block::lower_three_quarters_left_one_quarter_block)),
            '\u{1CEA6}' => Some((0x65, block::upper_three_quarters_left_one_quarter_block)),
            '\u{1CEA7}' => Some((0x57, block::upper_half_left_one_quarter_block)),
            '\u{1CEA8}' => Some((0x14, block::left_half_upper_one_quarter_block)),
            '\u{1CEA9}' => Some((0x1C, block::left_three_quarters_upper_one_quarter_block)),
            '\u{1CEAA}' => Some((0x4E, block::right_three_quarters_upper_one_quarter_block)),
            '\u{1CEAB}' => Some((0x47, block::right_half_upper_one_quarter_block)),
            '\u{1CEAC}' => Some((0x59, block::upper_half_right_one_quarter_block)),
            '\u{1CEAD}' => Some((0x66, block::upper_three_quarters_right_one_quarter_block)),
            '\u{1CEAE}' => Some((0x33, block::lower_three_quarters_right_one_quarter_block)),
            '\u{1CEAF}' => Some((0x26, block::lower_half_right_one_quarter_block)),
            '\u{1CEB0}'..='\u{1FB6F}' => None,
            '\u{1FB70}' => Some((0x67, block::vertical_one_eighth_block_2)),
            '\u{1FB71}' => Some((0x68, block::vertical_one_eighth_block_3)),
            '\u{1FB72}' => Some((0x69, block::vertical_one_eighth_block_4)),
            '\u{1FB73}' => Some((0x6A, block::vertical_one_eighth_block_5)),
            '\u{1FB74}' => Some((0x6B, block::vertical_one_eighth_block_6)),
            '\u{1FB75}' => Some((0x6C, block::vertical_one_eighth_block_7)),
            '\u{1FB76}' => Some((0x05, block::horizontal_one_eighth_block_2)),
            '\u{1FB77}' => Some((0x06, block::horizontal_one_eighth_block_3)),
            '\u{1FB78}' => Some((0x07, block::horizontal_one_eighth_block_4)),
            '\u{1FB79}' => Some((0x08, block::horizontal_one_eighth_block_5)),
            '\u{1FB7A}' => Some((0x09, block::horizontal_one_eighth_block_6)),
            '\u{1FB7B}' => Some((0x0A, block::horizontal_one_eighth_block_7)),
            '\u{1FB7C}' => Some((0x0D, block::left_and_lower_one_eighth_block)),
            '\u{1FB7D}' => Some((0x0E, block::left_and_upper_one_eighth_block)),
            '\u{1FB7E}' => Some((0x42, block::right_and_upper_one_eighth_block)),
            '\u{1FB7F}' => Some((0x41, block::right_and_lower_one_eighth_block)),
            '\u{1FB80}' => Some((0x4F, block::upper_and_lower_one_eighth_block)),
            '\u{1FB81}' => Some((0x04, block::horizontal_one_eighth_block_1358)),
            '\u{1FB82}' => Some((0x60, block::upper_one_quarter_block)),
            '\u{1FB83}' => Some((0x63, block::upper_three_eighths_block)),
            '\u{1FB84}' => Some((0x53, block::upper_five_eighths_block)),
            '\u{1FB85}' => Some((0x64, block::upper_three_quarters_block)),
            '\u{1FB86}' => Some((0x62, block::upper_seven_eighths_block)),
            '\u{1FB87}' => Some((0x49, block::right_one_quarter_block)),
            '\u{1FB88}' => Some((0x4B, block::right_three_eighths_block)),
            '\u{1FB89}' => Some((0x43, block::right_five_eighths_block)),
            '\u{1FB8A}' => Some((0x4C, block::right_three_quarters_block)),
            '\u{1FB8B}' => Some((0x4A, block::right_seven_eighths_block)),
            '\u{1FB8C}' => Some((0x13, block::left_half_medium_shade)),
            '\u{1FB8D}' => Some((0x46, block::right_half_medium_shade)),
            '\u{1FB8E}' => Some((0x58, block::upper_half_medium_shade)),
            '\u{1FB8F}' => Some((0x25, block::lower_half_medium_shade)),
            '\u{1FB90}' => Some((0x0C, block::inverse_medium_shade)),
            '\u{1FB91}' => Some((0x54, block::upper_half_block_and_lower_half_inverse_medium_shade)),
            '\u{1FB92}' => Some((0x56, block::upper_half_inverse_medium_shade_and_lower_half_block)),
            '\u{1FB93}' => None,
            '\u{1FB94}' => Some((0x11, block::left_half_inverse_medium_shade_and_right_half_block)),
            '\u{1FB95}' => Some((0x00, block::checker_board_fill)),
            '\u{1FB96}' => Some((0x0B, block::inverse_checker_board_fill)),
            '\u{1FB97}' => Some((0x03, block::heavy_horizontal_fill)),
            '\u{1FB98}'..='\u{1FBCD}' => None,
            '\u{1FBCE}' => Some((0x1D, block::left_two_thirds_block)),
            '\u{1FBCF}' => Some((0x17, block::left_one_third_block)),
            '\u{1FBD0}'..='\u{1FBE3}' => None,
            '\u{1FBE4}' => Some((0x51, block::upper_centre_one_quarter_block)),
            '\u{1FBE5}' => Some((0x20, block::lower_centre_one_quarter_block)),
            '\u{1FBE6}' => Some((0x35, block::middle_left_one_quarter_block)),
            '\u{1FBE7}' => Some((0x36, block::middle_right_one_quarter_block)),
            '\u{1FBE8}'.. => None,
        };

        result.map(|(id_offset, render)| Self {
            id: base_id::BLOCK_ELEMENTS + id_offset,
            key,
            render,
        })
    }

    fn try_block_sextants(key: char) -> Option<Self> {
        let result: Option<(_, Render)> = match key {
            ..='\u{1FAFF}' => None,
            '\u{1FB00}' => Some((0x00, block::block_sextant_1)),
            '\u{1FB01}' => Some((0x1E, block::block_sextant_2)),
            '\u{1FB02}' => Some((0x01, block::block_sextant_12)),
            '\u{1FB03}' => Some((0x2D, block::block_sextant_3)),
            '\u{1FB04}' => Some((0x10, block::block_sextant_13)),
            '\u{1FB05}' => Some((0x1F, block::block_sextant_23)),
            '\u{1FB06}' => Some((0x02, block::block_sextant_123)),
            '\u{1FB07}' => Some((0x35, block::block_sextant_4)),
            '\u{1FB08}' => Some((0x17, block::block_sextant_14)),
            '\u{1FB09}' => Some((0x27, block::block_sextant_24)),
            '\u{1FB0A}' => Some((0x09, block::block_sextant_124)),
            '\u{1FB0B}' => Some((0x2E, block::block_sextant_34)),
            '\u{1FB0C}' => Some((0x11, block::block_sextant_134)),
            '\u{1FB0D}' => Some((0x20, block::block_sextant_234)),
            '\u{1FB0E}' => Some((0x03, block::block_sextant_1234)),
            '\u{1FB0F}' => Some((0x39, block::block_sextant_5)),
            '\u{1FB10}' => Some((0x1B, block::block_sextant_15)),
            '\u{1FB11}' => Some((0x2A, block::block_sextant_25)),
            '\u{1FB12}' => Some((0x0D, block::block_sextant_125)),
            '\u{1FB13}' => Some((0x32, block::block_sextant_35)),
            '\u{1FB14}' => Some((0x24, block::block_sextant_235)),
            '\u{1FB15}' => Some((0x06, block::block_sextant_1235)),
            '\u{1FB16}' => Some((0x36, block::block_sextant_45)),
            '\u{1FB17}' => Some((0x18, block::block_sextant_145)),
            '\u{1FB18}' => Some((0x28, block::block_sextant_245)),
            '\u{1FB19}' => Some((0x0A, block::block_sextant_1245)),
            '\u{1FB1A}' => Some((0x2F, block::block_sextant_345)),
            '\u{1FB1B}' => Some((0x12, block::block_sextant_1345)),
            '\u{1FB1C}' => Some((0x21, block::block_sextant_2345)),
            '\u{1FB1D}' => Some((0x04, block::block_sextant_12345)),
            '\u{1FB1E}' => Some((0x3B, block::block_sextant_6)),
            '\u{1FB1F}' => Some((0x1D, block::block_sextant_16)),
            '\u{1FB20}' => Some((0x2C, block::block_sextant_26)),
            '\u{1FB21}' => Some((0x0F, block::block_sextant_126)),
            '\u{1FB22}' => Some((0x34, block::block_sextant_36)),
            '\u{1FB23}' => Some((0x16, block::block_sextant_136)),
            '\u{1FB24}' => Some((0x26, block::block_sextant_236)),
            '\u{1FB25}' => Some((0x08, block::block_sextant_1236)),
            '\u{1FB26}' => Some((0x38, block::block_sextant_46)),
            '\u{1FB27}' => Some((0x1A, block::block_sextant_146)),
            '\u{1FB28}' => Some((0x0C, block::block_sextant_1246)),
            '\u{1FB29}' => Some((0x31, block::block_sextant_346)),
            '\u{1FB2A}' => Some((0x14, block::block_sextant_1346)),
            '\u{1FB2B}' => Some((0x23, block::block_sextant_2346)),
            '\u{1FB2C}' => Some((0x05, block::block_sextant_12346)),
            '\u{1FB2D}' => Some((0x3A, block::block_sextant_56)),
            '\u{1FB2E}' => Some((0x1C, block::block_sextant_156)),
            '\u{1FB2F}' => Some((0x2B, block::block_sextant_256)),
            '\u{1FB30}' => Some((0x0E, block::block_sextant_1256)),
            '\u{1FB31}' => Some((0x33, block::block_sextant_356)),
            '\u{1FB32}' => Some((0x15, block::block_sextant_1356)),
            '\u{1FB33}' => Some((0x25, block::block_sextant_2356)),
            '\u{1FB34}' => Some((0x07, block::block_sextant_12356)),
            '\u{1FB35}' => Some((0x37, block::block_sextant_456)),
            '\u{1FB36}' => Some((0x19, block::block_sextant_1456)),
            '\u{1FB37}' => Some((0x29, block::block_sextant_2456)),
            '\u{1FB38}' => Some((0x0B, block::block_sextant_12456)),
            '\u{1FB39}' => Some((0x30, block::block_sextant_3456)),
            '\u{1FB3A}' => Some((0x13, block::block_sextant_13456)),
            '\u{1FB3B}' => Some((0x22, block::block_sextant_23456)),
            '\u{1FB3C}'.. => None,
        };

        result.map(|(id_offset, render)| Self {
            id: base_id::BLOCK_SEXTANTS + id_offset,
            key,
            render,
        })
    }

    fn try_block_octants(key: char) -> Option<Self> {
        let result: Option<(_, Render)> = match key {
            ..='\u{1CCFF}' => None,
            '\u{1CD00}' => Some((0xB0, block::block_octant_3)),
            '\u{1CD01}' => Some((0x75, block::block_octant_23)),
            '\u{1CD02}' => Some((0x00, block::block_octant_123)),
            '\u{1CD03}' => Some((0xCE, block::block_octant_4)),
            '\u{1CD04}' => Some((0x56, block::block_octant_14)),
            '\u{1CD05}' => Some((0x1B, block::block_octant_124)),
            '\u{1CD06}' => Some((0xB1, block::block_octant_34)),
            '\u{1CD07}' => Some((0x3A, block::block_octant_134)),
            '\u{1CD08}' => Some((0x76, block::block_octant_234)),
            '\u{1CD09}' => Some((0xDD, block::block_octant_5)),
            '\u{1CD0A}' => Some((0x66, block::block_octant_15)),
            '\u{1CD0B}' => Some((0xA1, block::block_octant_25)),
            '\u{1CD0C}' => Some((0x2B, block::block_octant_125)),
            '\u{1CD0D}' => Some((0x4A, block::block_octant_135)),
            '\u{1CD0E}' => Some((0x86, block::block_octant_235)),
            '\u{1CD0F}' => Some((0x0C, block::block_octant_1235)),
            '\u{1CD10}' => Some((0xCF, block::block_octant_45)),
            '\u{1CD11}' => Some((0x57, block::block_octant_145)),
            '\u{1CD12}' => Some((0x95, block::block_octant_245)),
            '\u{1CD13}' => Some((0x1C, block::block_octant_1245)),
            '\u{1CD14}' => Some((0xB2, block::block_octant_345)),
            '\u{1CD15}' => Some((0x3B, block::block_octant_1345)),
            '\u{1CD16}' => Some((0x77, block::block_octant_2345)),
            '\u{1CD17}' => Some((0x01, block::block_octant_12345)),
            '\u{1CD18}' => Some((0xE3, block::block_octant_6)),
            '\u{1CD19}' => Some((0x6E, block::block_octant_16)),
            '\u{1CD1A}' => Some((0xA9, block::block_octant_26)),
            '\u{1CD1B}' => Some((0x33, block::block_octant_126)),
            '\u{1CD1C}' => Some((0xC7, block::block_octant_36)),
            '\u{1CD1D}' => Some((0x50, block::block_octant_136)),
            '\u{1CD1E}' => Some((0x8E, block::block_octant_236)),
            '\u{1CD1F}' => Some((0x14, block::block_octant_1236)),
            '\u{1CD20}' => Some((0x5F, block::block_octant_146)),
            '\u{1CD21}' => Some((0x9B, block::block_octant_246)),
            '\u{1CD22}' => Some((0x24, block::block_octant_1246)),
            '\u{1CD23}' => Some((0xB9, block::block_octant_346)),
            '\u{1CD24}' => Some((0x43, block::block_octant_1346)),
            '\u{1CD25}' => Some((0x7F, block::block_octant_2346)),
            '\u{1CD26}' => Some((0x06, block::block_octant_12346)),
            '\u{1CD27}' => Some((0xDE, block::block_octant_56)),
            '\u{1CD28}' => Some((0x67, block::block_octant_156)),
            '\u{1CD29}' => Some((0xA2, block::block_octant_256)),
            '\u{1CD2A}' => Some((0x2C, block::block_octant_1256)),
            '\u{1CD2B}' => Some((0xC0, block::block_octant_356)),
            '\u{1CD2C}' => Some((0x4B, block::block_octant_1356)),
            '\u{1CD2D}' => Some((0x87, block::block_octant_2356)),
            '\u{1CD2E}' => Some((0x0D, block::block_octant_12356)),
            '\u{1CD2F}' => Some((0xD0, block::block_octant_456)),
            '\u{1CD30}' => Some((0x58, block::block_octant_1456)),
            '\u{1CD31}' => Some((0x96, block::block_octant_2456)),
            '\u{1CD32}' => Some((0x1D, block::block_octant_12456)),
            '\u{1CD33}' => Some((0xB3, block::block_octant_3456)),
            '\u{1CD34}' => Some((0x3C, block::block_octant_13456)),
            '\u{1CD35}' => Some((0x78, block::block_octant_23456)),
            '\u{1CD36}' => Some((0x72, block::block_octant_17)),
            '\u{1CD37}' => Some((0xAD, block::block_octant_27)),
            '\u{1CD38}' => Some((0x37, block::block_octant_127)),
            '\u{1CD39}' => Some((0xCB, block::block_octant_37)),
            '\u{1CD3A}' => Some((0x53, block::block_octant_137)),
            '\u{1CD3B}' => Some((0x92, block::block_octant_237)),
            '\u{1CD3C}' => Some((0x18, block::block_octant_1237)),
            '\u{1CD3D}' => Some((0xDA, block::block_octant_47)),
            '\u{1CD3E}' => Some((0x63, block::block_octant_147)),
            '\u{1CD3F}' => Some((0x9E, block::block_octant_247)),
            '\u{1CD40}' => Some((0x28, block::block_octant_1247)),
            '\u{1CD41}' => Some((0xBD, block::block_octant_347)),
            '\u{1CD42}' => Some((0x47, block::block_octant_1347)),
            '\u{1CD43}' => Some((0x83, block::block_octant_2347)),
            '\u{1CD44}' => Some((0x09, block::block_octant_12347)),
            '\u{1CD45}' => Some((0x6B, block::block_octant_157)),
            '\u{1CD46}' => Some((0xA6, block::block_octant_257)),
            '\u{1CD47}' => Some((0x30, block::block_octant_1257)),
            '\u{1CD48}' => Some((0xC4, block::block_octant_357)),
            '\u{1CD49}' => Some((0x8B, block::block_octant_2357)),
            '\u{1CD4A}' => Some((0x11, block::block_octant_12357)),
            '\u{1CD4B}' => Some((0xD4, block::block_octant_457)),
            '\u{1CD4C}' => Some((0x5C, block::block_octant_1457)),
            '\u{1CD4D}' => Some((0x21, block::block_octant_12457)),
            '\u{1CD4E}' => Some((0xB6, block::block_octant_3457)),
            '\u{1CD4F}' => Some((0x40, block::block_octant_13457)),
            '\u{1CD50}' => Some((0x7C, block::block_octant_23457)),
            '\u{1CD51}' => Some((0xE4, block::block_octant_67)),
            '\u{1CD52}' => Some((0x6F, block::block_octant_167)),
            '\u{1CD53}' => Some((0xAA, block::block_octant_267)),
            '\u{1CD54}' => Some((0x34, block::block_octant_1267)),
            '\u{1CD55}' => Some((0xC8, block::block_octant_367)),
            '\u{1CD56}' => Some((0x51, block::block_octant_1367)),
            '\u{1CD57}' => Some((0x8F, block::block_octant_2367)),
            '\u{1CD58}' => Some((0x15, block::block_octant_12367)),
            '\u{1CD59}' => Some((0xD7, block::block_octant_467)),
            '\u{1CD5A}' => Some((0x60, block::block_octant_1467)),
            '\u{1CD5B}' => Some((0x9C, block::block_octant_2467)),
            '\u{1CD5C}' => Some((0x25, block::block_octant_12467)),
            '\u{1CD5D}' => Some((0xBA, block::block_octant_3467)),
            '\u{1CD5E}' => Some((0x44, block::block_octant_13467)),
            '\u{1CD5F}' => Some((0x80, block::block_octant_23467)),
            '\u{1CD60}' => Some((0x07, block::block_octant_123467)),
            '\u{1CD61}' => Some((0xDF, block::block_octant_567)),
            '\u{1CD62}' => Some((0x68, block::block_octant_1567)),
            '\u{1CD63}' => Some((0xA3, block::block_octant_2567)),
            '\u{1CD64}' => Some((0x2D, block::block_octant_12567)),
            '\u{1CD65}' => Some((0xC1, block::block_octant_3567)),
            '\u{1CD66}' => Some((0x4C, block::block_octant_13567)),
            '\u{1CD67}' => Some((0x88, block::block_octant_23567)),
            '\u{1CD68}' => Some((0x0E, block::block_octant_123567)),
            '\u{1CD69}' => Some((0xD1, block::block_octant_4567)),
            '\u{1CD6A}' => Some((0x59, block::block_octant_14567)),
            '\u{1CD6B}' => Some((0x97, block::block_octant_24567)),
            '\u{1CD6C}' => Some((0x1E, block::block_octant_124567)),
            '\u{1CD6D}' => Some((0xB4, block::block_octant_34567)),
            '\u{1CD6E}' => Some((0x3D, block::block_octant_134567)),
            '\u{1CD6F}' => Some((0x79, block::block_octant_234567)),
            '\u{1CD70}' => Some((0x02, block::block_octant_1234567)),
            '\u{1CD71}' => Some((0x74, block::block_octant_18)),
            '\u{1CD72}' => Some((0xAF, block::block_octant_28)),
            '\u{1CD73}' => Some((0x39, block::block_octant_128)),
            '\u{1CD74}' => Some((0xCD, block::block_octant_38)),
            '\u{1CD75}' => Some((0x55, block::block_octant_138)),
            '\u{1CD76}' => Some((0x94, block::block_octant_238)),
            '\u{1CD77}' => Some((0x1A, block::block_octant_1238)),
            '\u{1CD78}' => Some((0xDC, block::block_octant_48)),
            '\u{1CD79}' => Some((0x65, block::block_octant_148)),
            '\u{1CD7A}' => Some((0xA0, block::block_octant_248)),
            '\u{1CD7B}' => Some((0x2A, block::block_octant_1248)),
            '\u{1CD7C}' => Some((0xBF, block::block_octant_348)),
            '\u{1CD7D}' => Some((0x49, block::block_octant_1348)),
            '\u{1CD7E}' => Some((0x85, block::block_octant_2348)),
            '\u{1CD7F}' => Some((0x0B, block::block_octant_12348)),
            '\u{1CD80}' => Some((0xE2, block::block_octant_58)),
            '\u{1CD81}' => Some((0x6D, block::block_octant_158)),
            '\u{1CD82}' => Some((0xA8, block::block_octant_258)),
            '\u{1CD83}' => Some((0x32, block::block_octant_1258)),
            '\u{1CD84}' => Some((0xC6, block::block_octant_358)),
            '\u{1CD85}' => Some((0x4F, block::block_octant_1358)),
            '\u{1CD86}' => Some((0x8D, block::block_octant_2358)),
            '\u{1CD87}' => Some((0x13, block::block_octant_12358)),
            '\u{1CD88}' => Some((0xD6, block::block_octant_458)),
            '\u{1CD89}' => Some((0x5E, block::block_octant_1458)),
            '\u{1CD8A}' => Some((0x9A, block::block_octant_2458)),
            '\u{1CD8B}' => Some((0x23, block::block_octant_12458)),
            '\u{1CD8C}' => Some((0xB8, block::block_octant_3458)),
            '\u{1CD8D}' => Some((0x42, block::block_octant_13458)),
            '\u{1CD8E}' => Some((0x7E, block::block_octant_23458)),
            '\u{1CD8F}' => Some((0x05, block::block_octant_123458)),
            '\u{1CD90}' => Some((0x71, block::block_octant_168)),
            '\u{1CD91}' => Some((0xAC, block::block_octant_268)),
            '\u{1CD92}' => Some((0x36, block::block_octant_1268)),
            '\u{1CD93}' => Some((0xCA, block::block_octant_368)),
            '\u{1CD94}' => Some((0x91, block::block_octant_2368)),
            '\u{1CD95}' => Some((0x17, block::block_octant_12368)),
            '\u{1CD96}' => Some((0xD9, block::block_octant_468)),
            '\u{1CD97}' => Some((0x62, block::block_octant_1468)),
            '\u{1CD98}' => Some((0x27, block::block_octant_12468)),
            '\u{1CD99}' => Some((0xBC, block::block_octant_3468)),
            '\u{1CD9A}' => Some((0x46, block::block_octant_13468)),
            '\u{1CD9B}' => Some((0x82, block::block_octant_23468)),
            '\u{1CD9C}' => Some((0xE0, block::block_octant_568)),
            '\u{1CD9D}' => Some((0x6A, block::block_octant_1568)),
            '\u{1CD9E}' => Some((0xA5, block::block_octant_2568)),
            '\u{1CD9F}' => Some((0x2F, block::block_octant_12568)),
            '\u{1CDA0}' => Some((0xC3, block::block_octant_3568)),
            '\u{1CDA1}' => Some((0x4D, block::block_octant_13568)),
            '\u{1CDA2}' => Some((0x8A, block::block_octant_23568)),
            '\u{1CDA3}' => Some((0x10, block::block_octant_123568)),
            '\u{1CDA4}' => Some((0xD3, block::block_octant_4568)),
            '\u{1CDA5}' => Some((0x5B, block::block_octant_14568)),
            '\u{1CDA6}' => Some((0x98, block::block_octant_24568)),
            '\u{1CDA7}' => Some((0x20, block::block_octant_124568)),
            '\u{1CDA8}' => Some((0xB5, block::block_octant_34568)),
            '\u{1CDA9}' => Some((0x3F, block::block_octant_134568)),
            '\u{1CDAA}' => Some((0x7B, block::block_octant_234568)),
            '\u{1CDAB}' => Some((0x03, block::block_octant_1234568)),
            '\u{1CDAC}' => Some((0x73, block::block_octant_178)),
            '\u{1CDAD}' => Some((0xAE, block::block_octant_278)),
            '\u{1CDAE}' => Some((0x38, block::block_octant_1278)),
            '\u{1CDAF}' => Some((0xCC, block::block_octant_378)),
            '\u{1CDB0}' => Some((0x54, block::block_octant_1378)),
            '\u{1CDB1}' => Some((0x93, block::block_octant_2378)),
            '\u{1CDB2}' => Some((0x19, block::block_octant_12378)),
            '\u{1CDB3}' => Some((0xDB, block::block_octant_478)),
            '\u{1CDB4}' => Some((0x64, block::block_octant_1478)),
            '\u{1CDB5}' => Some((0x9F, block::block_octant_2478)),
            '\u{1CDB6}' => Some((0x29, block::block_octant_12478)),
            '\u{1CDB7}' => Some((0xBE, block::block_octant_3478)),
            '\u{1CDB8}' => Some((0x48, block::block_octant_13478)),
            '\u{1CDB9}' => Some((0x84, block::block_octant_23478)),
            '\u{1CDBA}' => Some((0x0A, block::block_octant_123478)),
            '\u{1CDBB}' => Some((0xE1, block::block_octant_578)),
            '\u{1CDBC}' => Some((0x6C, block::block_octant_1578)),
            '\u{1CDBD}' => Some((0xA7, block::block_octant_2578)),
            '\u{1CDBE}' => Some((0x31, block::block_octant_12578)),
            '\u{1CDBF}' => Some((0xC5, block::block_octant_3578)),
            '\u{1CDC0}' => Some((0x4E, block::block_octant_13578)),
            '\u{1CDC1}' => Some((0x8C, block::block_octant_23578)),
            '\u{1CDC2}' => Some((0x12, block::block_octant_123578)),
            '\u{1CDC3}' => Some((0xD5, block::block_octant_4578)),
            '\u{1CDC4}' => Some((0x5D, block::block_octant_14578)),
            '\u{1CDC5}' => Some((0x99, block::block_octant_24578)),
            '\u{1CDC6}' => Some((0x22, block::block_octant_124578)),
            '\u{1CDC7}' => Some((0xB7, block::block_octant_34578)),
            '\u{1CDC8}' => Some((0x41, block::block_octant_134578)),
            '\u{1CDC9}' => Some((0x7D, block::block_octant_234578)),
            '\u{1CDCA}' => Some((0x04, block::block_octant_1234578)),
            '\u{1CDCB}' => Some((0xE5, block::block_octant_678)),
            '\u{1CDCC}' => Some((0x70, block::block_octant_1678)),
            '\u{1CDCD}' => Some((0xAB, block::block_octant_2678)),
            '\u{1CDCE}' => Some((0x35, block::block_octant_12678)),
            '\u{1CDCF}' => Some((0xC9, block::block_octant_3678)),
            '\u{1CDD0}' => Some((0x52, block::block_octant_13678)),
            '\u{1CDD1}' => Some((0x90, block::block_octant_23678)),
            '\u{1CDD2}' => Some((0x16, block::block_octant_123678)),
            '\u{1CDD3}' => Some((0xD8, block::block_octant_4678)),
            '\u{1CDD4}' => Some((0x61, block::block_octant_14678)),
            '\u{1CDD5}' => Some((0x9D, block::block_octant_24678)),
            '\u{1CDD6}' => Some((0x26, block::block_octant_124678)),
            '\u{1CDD7}' => Some((0xBB, block::block_octant_34678)),
            '\u{1CDD8}' => Some((0x45, block::block_octant_134678)),
            '\u{1CDD9}' => Some((0x81, block::block_octant_234678)),
            '\u{1CDDA}' => Some((0x08, block::block_octant_1234678)),
            '\u{1CDDB}' => Some((0x69, block::block_octant_15678)),
            '\u{1CDDC}' => Some((0xA4, block::block_octant_25678)),
            '\u{1CDDD}' => Some((0x2E, block::block_octant_125678)),
            '\u{1CDDE}' => Some((0xC2, block::block_octant_35678)),
            '\u{1CDDF}' => Some((0x89, block::block_octant_235678)),
            '\u{1CDE0}' => Some((0x0F, block::block_octant_1235678)),
            '\u{1CDE1}' => Some((0xD2, block::block_octant_45678)),
            '\u{1CDE2}' => Some((0x5A, block::block_octant_145678)),
            '\u{1CDE3}' => Some((0x1F, block::block_octant_1245678)),
            '\u{1CDE4}' => Some((0x3E, block::block_octant_1345678)),
            '\u{1CDE5}' => Some((0x7A, block::block_octant_2345678)),
            '\u{1CDE6}'.. => None,
        };

        result.map(|(id_offset, render)| Self {
            id: base_id::BLOCK_OCTANTS + id_offset,
            key,
            render,
        })
    }
}
